//! Coverage/profiling: tracks which Next disjuncts (actions) produced successors.
//!
//! When `--coverage` is enabled, the runtime tracks how many times each action
//! (disjunct of the Next relation) fires and how many successor states it produced.

use std::collections::BTreeMap;
use std::sync::atomic::{AtomicU64, Ordering};

/// Per-action coverage statistics.
#[derive(Debug, Clone, Default)]
pub struct ActionCoverageEntry {
    /// Number of times this action fired (produced at least one successor).
    pub fires: u64,
    /// Total successor states generated by this action.
    pub states_generated: u64,
    /// Cumulative wall-clock time spent evaluating this action, in nanoseconds.
    pub elapsed_nanos: u64,
}

/// Aggregated coverage statistics across all workers.
#[derive(Debug, Clone, Default)]
pub struct CoverageStats {
    /// Map from action name to coverage entry.
    pub actions: BTreeMap<String, ActionCoverageEntry>,
}

impl CoverageStats {
    /// Print a summary table of action coverage.
    pub fn print_summary(&self) {
        if self.actions.is_empty() {
            println!("Coverage: no action data collected");
            return;
        }

        println!();
        println!("Action Coverage Summary");
        println!("{:-<80}", "");
        println!(
            "{:<30} {:>10} {:>10} {:>12} {:>10}",
            "Action", "Fires", "States", "Time(ms)", "Avg(us)"
        );
        println!("{:-<80}", "");

        let mut total_fires = 0u64;
        let mut total_states = 0u64;
        let mut total_nanos = 0u64;

        for (name, entry) in &self.actions {
            let time_ms = entry.elapsed_nanos as f64 / 1_000_000.0;
            let avg_us = if entry.fires > 0 {
                (entry.elapsed_nanos as f64 / entry.fires as f64) / 1_000.0
            } else {
                0.0
            };
            println!(
                "{:<30} {:>10} {:>10} {:>12.1} {:>10.1}",
                name, entry.fires, entry.states_generated, time_ms, avg_us
            );
            total_fires += entry.fires;
            total_states += entry.states_generated;
            total_nanos += entry.elapsed_nanos;
        }

        println!("{:-<80}", "");
        let total_time_ms = total_nanos as f64 / 1_000_000.0;
        let total_avg_us = if total_fires > 0 {
            (total_nanos as f64 / total_fires as f64) / 1_000.0
        } else {
            0.0
        };
        println!(
            "{:<30} {:>10} {:>10} {:>12.1} {:>10.1}",
            "TOTAL", total_fires, total_states, total_time_ms, total_avg_us
        );

        // Show actions that never fired
        let never_fired: Vec<_> = self
            .actions
            .iter()
            .filter(|(_, e)| e.fires == 0)
            .map(|(name, _)| name.as_str())
            .collect();
        if !never_fired.is_empty() {
            println!();
            println!("Actions that never fired:");
            for name in never_fired {
                println!("  - {}", name);
            }
        }
    }
}

/// Thread-safe coverage tracker using atomic counters.
#[derive(Debug)]
pub struct CoverageTracker {
    /// Parallel arrays: action_names[i] corresponds to fires[i] and states[i].
    action_names: Vec<String>,
    fires: Vec<AtomicU64>,
    states_generated: Vec<AtomicU64>,
    elapsed_nanos: Vec<AtomicU64>,
}

impl CoverageTracker {
    /// Create a new tracker for the given action names.
    pub fn new(action_names: Vec<String>) -> Self {
        let n = action_names.len();
        let fires = (0..n).map(|_| AtomicU64::new(0)).collect();
        let states_generated = (0..n).map(|_| AtomicU64::new(0)).collect();
        let elapsed_nanos = (0..n).map(|_| AtomicU64::new(0)).collect();
        Self {
            action_names,
            fires,
            states_generated,
            elapsed_nanos,
        }
    }

    /// Record that action at index `idx` fired and produced `num_states` successors.
    pub fn record(&self, idx: usize, num_states: u64) {
        if idx < self.fires.len() {
            self.fires[idx].fetch_add(1, Ordering::Relaxed);
            self.states_generated[idx].fetch_add(num_states, Ordering::Relaxed);
        }
    }

    /// Record that action at index `idx` fired, produced `num_states` successors,
    /// and took `elapsed_nanos` wall-clock nanoseconds to evaluate.
    pub fn record_with_time(&self, idx: usize, num_states: u64, elapsed_nanos: u64) {
        if idx < self.fires.len() {
            self.fires[idx].fetch_add(1, Ordering::Relaxed);
            self.states_generated[idx].fetch_add(num_states, Ordering::Relaxed);
            self.elapsed_nanos[idx].fetch_add(elapsed_nanos, Ordering::Relaxed);
        }
    }

    /// Snapshot the current coverage statistics.
    pub fn snapshot(&self) -> CoverageStats {
        let mut actions = BTreeMap::new();
        for (i, name) in self.action_names.iter().enumerate() {
            actions.insert(
                name.clone(),
                ActionCoverageEntry {
                    fires: self.fires[i].load(Ordering::Relaxed),
                    states_generated: self.states_generated[i].load(Ordering::Relaxed),
                    elapsed_nanos: self.elapsed_nanos[i].load(Ordering::Relaxed),
                },
            );
        }
        CoverageStats { actions }
    }
}
