//! Coverage/profiling: tracks which Next disjuncts (actions) produced successors.
//!
//! When `--coverage` is enabled, the runtime tracks how many times each action
//! (disjunct of the Next relation) fires and how many successor states it produced.

use std::collections::BTreeMap;
use std::sync::atomic::{AtomicU64, Ordering};

/// Per-action coverage statistics.
#[derive(Debug, Clone, Default)]
pub struct ActionCoverageEntry {
    /// Number of times this action fired (produced at least one successor).
    pub fires: u64,
    /// Total successor states generated by this action.
    pub states_generated: u64,
}

/// Aggregated coverage statistics across all workers.
#[derive(Debug, Clone, Default)]
pub struct CoverageStats {
    /// Map from action name to coverage entry.
    pub actions: BTreeMap<String, ActionCoverageEntry>,
}

impl CoverageStats {
    /// Print a summary table of action coverage.
    pub fn print_summary(&self) {
        if self.actions.is_empty() {
            println!("Coverage: no action data collected");
            return;
        }

        println!();
        println!("Action Coverage Summary");
        println!("{:-<60}", "");
        println!(
            "{:<35} {:>10} {:>12}",
            "Action", "Fires", "States"
        );
        println!("{:-<60}", "");

        let mut total_fires = 0u64;
        let mut total_states = 0u64;

        for (name, entry) in &self.actions {
            println!(
                "{:<35} {:>10} {:>12}",
                name, entry.fires, entry.states_generated
            );
            total_fires += entry.fires;
            total_states += entry.states_generated;
        }

        println!("{:-<60}", "");
        println!(
            "{:<35} {:>10} {:>12}",
            "TOTAL", total_fires, total_states
        );

        // Show actions that never fired
        let never_fired: Vec<_> = self
            .actions
            .iter()
            .filter(|(_, e)| e.fires == 0)
            .map(|(name, _)| name.as_str())
            .collect();
        if !never_fired.is_empty() {
            println!();
            println!("Actions that never fired:");
            for name in never_fired {
                println!("  - {}", name);
            }
        }
    }
}

/// Thread-safe coverage tracker using atomic counters.
#[derive(Debug)]
pub struct CoverageTracker {
    /// Parallel arrays: action_names[i] corresponds to fires[i] and states[i].
    action_names: Vec<String>,
    fires: Vec<AtomicU64>,
    states_generated: Vec<AtomicU64>,
}

impl CoverageTracker {
    /// Create a new tracker for the given action names.
    pub fn new(action_names: Vec<String>) -> Self {
        let n = action_names.len();
        let fires = (0..n).map(|_| AtomicU64::new(0)).collect();
        let states_generated = (0..n).map(|_| AtomicU64::new(0)).collect();
        Self {
            action_names,
            fires,
            states_generated,
        }
    }

    /// Record that action at index `idx` fired and produced `num_states` successors.
    pub fn record(&self, idx: usize, num_states: u64) {
        if idx < self.fires.len() {
            self.fires[idx].fetch_add(1, Ordering::Relaxed);
            self.states_generated[idx].fetch_add(num_states, Ordering::Relaxed);
        }
    }

    /// Snapshot the current coverage statistics.
    pub fn snapshot(&self) -> CoverageStats {
        let mut actions = BTreeMap::new();
        for (i, name) in self.action_names.iter().enumerate() {
            actions.insert(
                name.clone(),
                ActionCoverageEntry {
                    fires: self.fires[i].load(Ordering::Relaxed),
                    states_generated: self.states_generated[i].load(Ordering::Relaxed),
                },
            );
        }
        CoverageStats { actions }
    }
}
